#!/usr/bin/python3

from setuptools import setup

setup(
    name='Linked-Connections-Server-Faker',
    version='0.0.1',
    packages=['venv.lib.python3.7.site-packages.zc.lockfile', 'venv.lib.python3.7.site-packages.pip',
              'venv.lib.python3.7.site-packages.pip._vendor', 'venv.lib.python3.7.site-packages.pip._vendor.idna',
              'venv.lib.python3.7.site-packages.pip._vendor.pep517',
              'venv.lib.python3.7.site-packages.pip._vendor.pytoml',
              'venv.lib.python3.7.site-packages.pip._vendor.certifi',
              'venv.lib.python3.7.site-packages.pip._vendor.chardet',
              'venv.lib.python3.7.site-packages.pip._vendor.chardet.cli',
              'venv.lib.python3.7.site-packages.pip._vendor.distlib',
              'venv.lib.python3.7.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python3.7.site-packages.pip._vendor.msgpack',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.util',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.contrib',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.packages',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.7.site-packages.pip._vendor.colorama',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.7.site-packages.pip._vendor.lockfile',
              'venv.lib.python3.7.site-packages.pip._vendor.progress',
              'venv.lib.python3.7.site-packages.pip._vendor.requests',
              'venv.lib.python3.7.site-packages.pip._vendor.packaging',
              'venv.lib.python3.7.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python3.7.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.7.site-packages.pip._vendor.webencodings',
              'venv.lib.python3.7.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python3.7.site-packages.pip._internal', 'venv.lib.python3.7.site-packages.pip._internal.cli',
              'venv.lib.python3.7.site-packages.pip._internal.req',
              'venv.lib.python3.7.site-packages.pip._internal.vcs',
              'venv.lib.python3.7.site-packages.pip._internal.utils',
              'venv.lib.python3.7.site-packages.pip._internal.models',
              'venv.lib.python3.7.site-packages.pip._internal.commands',
              'venv.lib.python3.7.site-packages.pip._internal.operations', 'venv.lib.python3.7.site-packages.idna',
              'venv.lib.python3.7.site-packages.pytz', 'venv.lib.python3.7.site-packages.jaraco',
              'venv.lib.python3.7.site-packages.certifi', 'venv.lib.python3.7.site-packages.chardet',
              'venv.lib.python3.7.site-packages.chardet.cli', 'venv.lib.python3.7.site-packages.cheroot',
              'venv.lib.python3.7.site-packages.cheroot.ssl', 'venv.lib.python3.7.site-packages.cheroot.test',
              'venv.lib.python3.7.site-packages.cheroot.workers', 'venv.lib.python3.7.site-packages.tempora',
              'venv.lib.python3.7.site-packages.urllib3', 'venv.lib.python3.7.site-packages.urllib3.util',
              'venv.lib.python3.7.site-packages.urllib3.contrib',
              'venv.lib.python3.7.site-packages.urllib3.contrib._securetransport',
              'venv.lib.python3.7.site-packages.urllib3.packages',
              'venv.lib.python3.7.site-packages.urllib3.packages.backports',
              'venv.lib.python3.7.site-packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.7.site-packages.cherrypy', 'venv.lib.python3.7.site-packages.cherrypy.lib',
              'venv.lib.python3.7.site-packages.cherrypy.test', 'venv.lib.python3.7.site-packages.cherrypy.process',
              'venv.lib.python3.7.site-packages.cherrypy.scaffold',
              'venv.lib.python3.7.site-packages.cherrypy.tutorial', 'venv.lib.python3.7.site-packages.dateutil',
              'venv.lib.python3.7.site-packages.dateutil.tz', 'venv.lib.python3.7.site-packages.dateutil.parser',
              'venv.lib.python3.7.site-packages.dateutil.zoneinfo', 'venv.lib.python3.7.site-packages.requests',
              'venv.lib.python3.7.site-packages.backports', 'venv.lib.python3.7.site-packages.more_itertools',
              'venv.lib.python3.7.site-packages.more_itertools.tests'],
    url='https://git.dylanvanassche.be/DylanVanAssche/Linked-Connections-Faker',
    license='GPLv3 or later',
    author='Dylan Van Assche',
    author_email='dylan.van.assche@protonmail.com',
    description=' A Linked Connections Server Faker written in Python 3 and Cherrypy. '
)
